### ISSUE TITLE
SaveNameStorageMixin for Attachment

### ISSUE THREAD

**Issue by domdinicola** [unicef/etools#1063]
Looks like this class has been introduced, it generates problems during the migrations with AzureStorage.
We discussed this internally and we don't need this since what is done in SaveNameStorageMixin is done already by AzureStorage.
Is not a good idea to create a migration which use a function not written in the migration itself (since that can change during the lifecicle development).
We suggest to remove the utils.files.storage.SaveNameDefaultStorage() function for storage in the Attachment (file field) and use the standard Django storage (as I said before AzureStorage will take care of duplicate names and truncation)

**Comment by ntrncic** [comment]
@pitsevich please add doc strings to any new classes methods. It's hard to understand what the code is trying to do.

**Comment by pitsevich** [comment]
@domdinicola @ntrncic I think I agree and it's best to have that removed.

but a few words on why this was added.

we had 2 issues reported on Auditor Portal module -  [one](https://trello.com/c/3o1mUZ4t/122-random-text-appearing-at-the-end-of-an-attachment) & [two](https://trello.com/c/LbubUh1b/57-252-file-attachments-dont-retain-the-original-file-name).

basically, both of them are QA findings about random hashes sometimes being added to the end of filenames (that's what the detault storage back-end does in case when a file is uploaded with existing name).

in order to fix this, we've added this mixin which creates a sub-folder with hash name, which keeps the original file names.

However, it is probably an overkill for this case - which makes things more complicated than they should be.

I think we'll remove this code, and will mark this ticket as wont-fix:
https://trello.com/c/3o1mUZ4t/122-random-text-appearing-at-the-end-of-an-attachment

@ntrncic sounds good?
