### ISSUE TITLE
Change Locations PR Fix

### ISSUE THREAD

**Issue by ntrncic** [unicef/etools#309]
Errors are appearing when running tests. ImportError: The ``fake-factory`` package is now called ``Faker``. This is on PR #201 
Refer to https://circleci.com/gh/unicef/etools/1291

**Comment by n1207n** [comment]
@ntrncic,

I found the issue. factory-boy library relies on fake-factory package. Literally few hours ago, fake-factory PyPi is deprecated in favor of new package name at version 0.7.5.

![screen shot 2016-12-16 at 11 01 21 am](https://cloud.githubusercontent.com/assets/3138217/21274927/64bd2cd6-c37f-11e6-87bd-c8bbb2a81e0e.png)

factory-boy has a pip requirement of `Faker>=0.7.0`. If we somehow override this in our requirements file, factory-boy would start working again.

In the meantime, I'll make a PR issue for factory-boy so that they know this incident as well.

**Comment by robertavram** [comment]
ok.. make a PR in our repo to fix this in the requirements... thanks @n1207n !!!!
